### ISSUE TITLE
 Maven Build Failure on prospero-standalone-galleon-pack

### ISSUE THREAD

**Issue by parsharma** [wildfly-extras/prospero#713]
While running the command mvn clean install -Pdist -DskipTests, the build fails at the prospero-standalone-galleon-pack module with the following error:

[ERROR] Failed to execute goal org.wildfly.galleon-plugins:wildfly-galleon-maven-plugin:7.1.0.Final:build-feature-pack (prospero-galleon-pack-build) on project prospero-standalone-galleon-pack: Failed to resolve org.jboss.logging:logging-parent:pom:1.0.1.Final: The following artifacts could not be resolved: org.jboss.logging:logging-parent:pom:1.0.1.Final (present, but unavailable): Cannot access jboss-public-repository (https://repository.jboss.org/nexus/content/groups/public/) in offline mode and the artifact org.jboss.logging:logging-parent:pom:1.0.1.Final has not been downloaded from it before. -> [Help 1]

**Comment by spyrkob** [comment]
Does the settings.xml define any repositories or pluginRepositories configuration? Can you check the `.m2/repository/org/jboss/logging/logging-parent/1.0.1.Final/_remote.repositories` and see what repository it is downloaded from?

**Comment by spyrkob** [comment]
Looks like somehow that artifact is downloaded from repository with id `jboss-public-repository-group` while prospero uses `jboss-public-repository`. I don't really know why that would happen, I don't think I've ever seen that.

**Comment by parsharma** [comment]
Is there option where we can change id manually? So it will download the repo from jboss-public-repository.

**Comment by TomasHofman** [comment]
The `jboss-public-repository-group` is ID used in Wildfly, which we were building just before prospero (https://github.com/wildfly/wildfly/blob/main/pom.xml#L896), which is probably why it's marked there as such.

In any case if the artifact is present in the Maven cache, it should be used and not downloaded again.

**Comment by TomasHofman** [comment]
This is where I think the plugin sets an offline session in the build-feature-pack goal: https://github.com/wildfly/galleon-plugins/blob/main/maven-plugin/src/main/java/org/wildfly/galleon/maven/AbstractFeaturePackBuildMojo.java#L443

**Comment by spyrkob** [comment]
>In any case if the artifact is present in the Maven cache, it should be used and not downloaded again.

This is not quite how the maven cache works. Artifact is resolved from cache only if it was previously downloaded from the same repository.

**Comment by TomasHofman** [comment]
I don't think that's what I'm observing. That would mean artifacts would get constantly overwritten based on which project I built last.

Right now I see this in my cache:

```
logging-parent-1.0.1.Final.pom>jboss-public-repository-group=
```

After rebuilding prespero, I still see the same repository ID in the metadata file and I didn't see this POM being downloaded.

**Comment by spyrkob** [comment]
If the artifact has been downloaded previously from `jboss-public-repository-group` and now is requested from `jboss-public-repository`, Maven will first attempt to verify that the artifact is available in `jboss-public-repository`. If it is, it will not be downloaded again. [DefaultArtifactResolver.java](https://github.com/apache/maven-resolver/blob/1a3e9fde1d935778026f6a27bf127ae79f63d2f6/maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultArtifactResolver.java#L395-L475)

In case of logging-parent there's an additional layer of complexity in that it's a transitive dependency of jboss-logging which defines it's own repositories including `jboss-public-repository-group`. When resolving it during the actual project build it's correctly resolved from `jboss-public-repository-group` (even in offline mode), however the galleon-plugin seem to [only resolve artifacts from the repositories defined in the project](https://github.com/wildfly/galleon-plugins/blob/main/maven-plugin/src/main/java/org/wildfly/galleon/maven/ArtifactListBuilder.java#L116). IMO that seems to be an issue in the galleon-plugin itself.

**Comment by parsharma** [comment]
I've updated the POM.xml according to the PR, and now the issue is resolved. Why was it only failing on my laptop and not on other systems?
